// <auto-generated />
using System;
using Estoque.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Estoque.Infrastructure.Migrations
{
    [DbContext(typeof(EstoqueDbContext))]
    [Migration("20260712000000_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Estoque.Domain.ProdutoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("QuantidadeDisponivel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NomeProduto")
                        .IsUnique();

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
